2024-11-05 09:16:35,394 - [INFO] - backend_server.py[8]: 日志开启了~~~
2024-11-05 09:16:35,403 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:16:35,416 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:16:35,416 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:16:35,417 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:16:35,417 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:16:35,418 - [WARNING] - mysql_util.py[142]: 在metadata已经存在了数据表backend_logs_monitor,故没有进行数据表的创建
2024-11-05 09:16:35,418 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:16:35,420 - [WARNING] - mysql_util.py[142]: 在retail已经存在了数据表backend_logs,故没有进行数据表的创建
2024-11-05 09:16:35,421 - [INFO] - backend_server.py[44]: 获取所有的文件名['D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-00.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-01.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-02.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-03.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-04.log']
2024-11-05 09:16:35,421 - [INFO] - backend_server.py[52]: 获取处理过的文件名列表[]
2024-11-05 09:16:51,998 - [INFO] - backend_server.py[8]: 日志开启了~~~
2024-11-05 09:16:52,007 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:16:52,008 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:16:52,008 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:16:52,008 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:16:52,009 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:16:52,010 - [WARNING] - mysql_util.py[142]: 在metadata已经存在了数据表backend_logs_monitor,故没有进行数据表的创建
2024-11-05 09:16:52,010 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:16:52,011 - [WARNING] - mysql_util.py[142]: 在retail已经存在了数据表backend_logs,故没有进行数据表的创建
2024-11-05 09:16:52,011 - [INFO] - backend_server.py[44]: 获取所有的文件名['D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-00.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-01.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-02.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-03.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-04.log']
2024-11-05 09:16:52,012 - [INFO] - backend_server.py[52]: 获取处理过的文件名列表[]
2024-11-05 09:17:51,432 - [INFO] - backend_server.py[8]: 日志开启了~~~
2024-11-05 09:17:51,441 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:17:51,466 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:17:51,467 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:17:51,467 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:17:51,467 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:17:51,469 - [WARNING] - mysql_util.py[142]: 在metadata已经存在了数据表backend_logs_monitor,故没有进行数据表的创建
2024-11-05 09:17:51,470 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:17:51,471 - [WARNING] - mysql_util.py[142]: 在retail已经存在了数据表backend_logs,故没有进行数据表的创建
2024-11-05 09:17:51,471 - [INFO] - backend_server.py[44]: 获取所有的文件名['D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-00.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-01.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-02.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-03.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-04.log']
2024-11-05 09:17:51,472 - [INFO] - backend_server.py[52]: 获取处理过的文件名列表[]
2024-11-05 09:18:25,403 - [INFO] - backend_server.py[8]: 日志开启了~~~
2024-11-05 09:18:25,412 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:18:25,442 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:18:25,442 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:18:25,443 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:18:25,443 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:18:25,444 - [WARNING] - mysql_util.py[142]: 在metadata已经存在了数据表backend_logs_monitor,故没有进行数据表的创建
2024-11-05 09:18:25,444 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:18:25,446 - [WARNING] - mysql_util.py[142]: 在retail已经存在了数据表backend_logs,故没有进行数据表的创建
2024-11-05 09:18:25,446 - [INFO] - backend_server.py[44]: 获取所有的文件名['D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-00.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-01.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-02.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-03.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data/2024-11-04-17-42-04.log']
2024-11-05 09:18:25,447 - [INFO] - backend_server.py[52]: 获取处理过的文件名列表[]
2024-11-05 09:21:12,170 - [INFO] - backend_server.py[9]: ~~~~日志开启~~~~
2024-11-05 09:21:12,179 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:21:12,191 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:21:12,191 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:21:12,193 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:21:12,193 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:21:12,194 - [WARNING] - mysql_util.py[142]: 在metadata已经存在了数据表backend_logs_monitor,故没有进行数据表的创建
2024-11-05 09:21:12,194 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:21:12,195 - [WARNING] - mysql_util.py[142]: 在retail已经存在了数据表backend_logs,故没有进行数据表的创建
2024-11-05 09:21:12,195 - [INFO] - backend_server.py[45]: 获取所有的文件名['D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-00.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-01.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-02.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-03.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-04.log']
2024-11-05 09:21:12,196 - [INFO] - backend_server.py[54]: 获取处理过的文件名字[]
2024-11-05 09:21:12,196 - [INFO] - backend_server.py[57]: 获取需要处理的文件名['D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-00.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-01.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-02.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-03.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-04.log']
2024-11-05 09:25:08,442 - [INFO] - backend_server.py[9]: ~~~~日志开启~~~~
2024-11-05 09:25:08,451 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:25:08,452 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:25:08,452 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:25:08,452 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:25:08,453 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:25:08,454 - [WARNING] - mysql_util.py[142]: 在metadata已经存在了数据表backend_logs_monitor,故没有进行数据表的创建
2024-11-05 09:25:08,454 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:25:08,454 - [WARNING] - mysql_util.py[142]: 在retail已经存在了数据表backend_logs,故没有进行数据表的创建
2024-11-05 09:25:08,455 - [INFO] - backend_server.py[45]: 获取所有的文件名['D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-00.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-01.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-02.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-03.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-04.log']
2024-11-05 09:25:08,455 - [INFO] - backend_server.py[54]: 获取处理过的文件名字[]
2024-11-05 09:25:08,455 - [INFO] - backend_server.py[58]: 获取需要处理的文件名['D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-00.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-01.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-02.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-03.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-04.log']
2024-11-05 09:28:06,048 - [INFO] - backend_server.py[9]: ~~~~日志开启~~~~
2024-11-05 09:28:06,059 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:28:06,060 - [INFO] - mysql_util.py[29]: 创建链接localhost:3306//root, 成功!!!
2024-11-05 09:28:06,060 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:28:06,060 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:28:06,061 - [INFO] - mysql_util.py[49]: 切换了数据库metadata
2024-11-05 09:28:06,062 - [WARNING] - mysql_util.py[142]: 在metadata已经存在了数据表backend_logs_monitor,故没有进行数据表的创建
2024-11-05 09:28:06,062 - [INFO] - mysql_util.py[49]: 切换了数据库retail
2024-11-05 09:28:06,063 - [WARNING] - mysql_util.py[142]: 在retail已经存在了数据表backend_logs,故没有进行数据表的创建
2024-11-05 09:28:06,063 - [INFO] - backend_server.py[45]: 获取所有的文件名['D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-00.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-01.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-02.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-03.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-04.log']
2024-11-05 09:28:06,064 - [INFO] - backend_server.py[54]: 获取处理过的文件名字[]
2024-11-05 09:28:06,064 - [INFO] - backend_server.py[58]: 获取需要处理的文件名['D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-00.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-01.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-02.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-03.log', 'D:/Python/Pycharm/project/ETL1/logs/log_data//2024-11-04-17-42-04.log']
